version: 38
jobs:
- name: Sync
  steps:
  - !PushRepository
    name: Push to Remote
    remoteUrl: https://github.com/khose-ie/em-soft-framework-example.git
    userName: khose-ie
    passwordSecret: GITHUB_TOKEN
    force: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger
    branches: master
  - !TagCreateTrigger
    branches: master
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
