APPINCLUDE += -I$(srctree)/libs/STMicroelectronics/bsp/stm32h5xx-nucleo \
              -I$(srctree)/platform/stm/nucleo-h563zi/Core/Inc

obj-y += startup_stm32h563xx.o
obj-y += STM32H563xx_FLASH.o
obj-y += Core/Src/main.o
obj-y += Core/Src/stm32h5xx_it.o
obj-y += Core/Src/stm32h5xx_hal_msp.o
obj-y += Core/Src/sysmem.o
obj-y += Core/Src/syscalls.o
obj-y += Core/Src/system_stm32h5xx.o

obj-y += ../../../libs/STMicroelectronics/driver/stm32h5xx-hal-driver/Src/stm32h5xx_hal.o
obj-y += ../../../libs/STMicroelectronics/driver/stm32h5xx-hal-driver/Src/stm32h5xx_hal_cortex.o
obj-y += ../../../libs/STMicroelectronics/driver/stm32h5xx-hal-driver/Src/stm32h5xx_hal_icache.o
obj-y += ../../../libs/STMicroelectronics/driver/stm32h5xx-hal-driver/Src/stm32h5xx_hal_rcc.o
obj-y += ../../../libs/STMicroelectronics/driver/stm32h5xx-hal-driver/Src/stm32h5xx_hal_rcc_ex.o
obj-y += ../../../libs/STMicroelectronics/driver/stm32h5xx-hal-driver/Src/stm32h5xx_hal_flash.o
obj-y += ../../../libs/STMicroelectronics/driver/stm32h5xx-hal-driver/Src/stm32h5xx_hal_flash_ex.o
obj-y += ../../../libs/STMicroelectronics/driver/stm32h5xx-hal-driver/Src/stm32h5xx_hal_gpio.o
obj-y += ../../../libs/STMicroelectronics/driver/stm32h5xx-hal-driver/Src/stm32h5xx_hal_dma.o
obj-y += ../../../libs/STMicroelectronics/driver/stm32h5xx-hal-driver/Src/stm32h5xx_hal_dma_ex.o
obj-y += ../../../libs/STMicroelectronics/driver/stm32h5xx-hal-driver/Src/stm32h5xx_hal_pwr.o
obj-y += ../../../libs/STMicroelectronics/driver/stm32h5xx-hal-driver/Src/stm32h5xx_hal_pwr_ex.o
obj-y += ../../../libs/STMicroelectronics/driver/stm32h5xx-hal-driver/Src/stm32h5xx_hal_exti.o
obj-y += ../../../libs/STMicroelectronics/driver/stm32h5xx-hal-driver/Src/stm32h5xx_hal_usart.o
obj-y += ../../../libs/STMicroelectronics/driver/stm32h5xx-hal-driver/Src/stm32h5xx_hal_usart_ex.o
obj-y += ../../../libs/STMicroelectronics/driver/stm32h5xx-hal-driver/Src/stm32h5xx_hal_uart_ex.o
obj-y += ../../../libs/STMicroelectronics/driver/stm32h5xx-hal-driver/Src/stm32h5xx_hal_uart.o

obj-y += ../../../libs/STMicroelectronics/bsp/stm32h5xx-nucleo/stm32h5xx_nucleo.o
